services:
  postgres:
    image: postgres:16
    container_name: memorizez-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${MEMORIZEZ_DB_NAME}
      POSTGRES_USER: ${MEMORIZEZ_DB_USER}
      POSTGRES_PASSWORD: ${MEMORIZEZ_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - memorizez-postgres-data:/var/lib/postgresql/data

volumes:
  memorizez-postgres-data: